kafka:
  brokers: localhost:29092
generators:
  - topic: sample_topic
    partitionKey: any
    template: |-
      {
        "name": "{{ personName }}",
        "email": "{{ email }}",
        "from_address": "{{ ethereumAddress }}",
        "to_address": "{{ ethereumAddress }}",
        "amount": "{{ intBetween 1 1000 }}",
        "timestamp": "{{ timestamp }}"
      }
    number: 5
    loop: true
    delay: 2s
