kafka:
  brokers: localhost:29092
generators:
  - topic: sample_topic
    partitionKey: nil
    schema: |-
      {
        "from_address": "::ethereum_address()",
        "to_address": "::ethereum_address()",
        "amount": "::number(1,10)",
        "timestamp": "::timestamp()"
      }
    number: 5
    loop: true
    delay: 2s