kafka:
  brokers: localhost:9002
generators:
  - topic: sample_topic
    partitionKey:
    schema: |-
      {
        "name": "{{ personName }}",
        "email": "{{ email }}",
        "from_address": "{{ ethereumAddress }}",
        "to_address": "{{ ethereumAddress }}",
        "amount": "{{ intBetween 1 1000 }}",
        "timestamp": "{{ timestamp }}"
      }
    number: 5
    loop: true
    delay: 2s
